### ISSUE TITLE
Add last indexed block

### ISSUE THREAD

**Issue by fmrsabino** [gnosis/safe-services-status#13]
In order to provide better visibility on the indexing status of each chain, we should show the latest indexed block number for that chain.

@gnosis/safe-services

**Comment by fmrsabino** [comment]
Currently upptime allows to run custom javascript on the root status page (https://upptime.js.org/docs/configuration/#custom-javascript). However the root page contains not only entries for the core services but also for the client gateway.

A solution would be to:
1. Run custom javascript to fetch the blocks for all networks (need to keep a hardcoded list with the endpoints for all networks)
2. Update the entries (HTML) with the block number – accessing the specific `div` block might not be straightforward as the ids are generated.

**Comment by Uxio0** [comment]
That seems a little overcomplicated. I opened #14

**Comment by rmeissner** [comment]
Close in favor of #14
